import {readFile,writeFile,mkdir} from 'node:fs/promises';import {createServer} from 'node:http';import {createHash,randomBytes} from 'node:crypto';import {gzipSync} from 'node:zlib';import os from 'node:os';
const hash=x=>createHash('sha256').update(x).digest('hex'),out='docs/evaluation/vina_prepared_2026-09-13';await mkdir(out,{recursive:true});
const evidence=JSON.parse(await readFile(out+'/equivalence.json'));if(evidence.rows.length!==3||evidence.rows.some(r=>!r.exact))throw Error('Equivalence gate');const row=evidence.rows.find(r=>r.target==='fa10'),target=JSON.parse(await readFile('docs/evaluation/adaptive_docking_2026-09-08/science_inputs.json')).targets.find(t=>t.target==='fa10');
const assets=new Map();function asset(name,bytes,type){const digest=hash(bytes),url='/assets/'+digest+'/'+name;assets.set(url,{bytes,gzip:gzipSync(bytes,{level:9}),type});return {url,digest};}
const wasm=asset('vina_tasks.wasm',await readFile('tmp/vina-prepared/vina_tasks.wasm'),'application/wasm'),mod=asset('vina_tasks.mjs',await readFile('tmp/vina-prepared/vina_tasks.mjs'),'text/javascript'),receptor=asset('receptor.pdbqt',await readFile(target.receptor),'text/plain'),ligand=asset('ligand.pdbqt',await readFile(target.ligands.find(l=>l.id==='crystal').source.path),'text/plain'),prepared=asset('prepared.bin',await readFile('tmp/vina-prepared/artifacts/fa10.bin'),'application/octet-stream');
if(prepared.digest!==row.artifact.sha256||receptor.digest!==row.artifact.receptor_sha256||ligand.digest!==row.artifact.ligand_sha256)throw Error('Artifact provenance');
const httpsTest=process.env.VINA_PREPARED_HTTPS==='1',idb=httpsTest||process.env.VINA_PREPARED_IDB==='1',port=httpsTest?8770:idb?8769:8768;
const manifest={require_webcrypto:httpsTest,transport_experiment:httpsTest?'https-tunnel-v1':'lan-v1',cache_policy:idb?'indexeddb-v1':'http-only-v1',module_url:mod.url,wasm_url:wasm.url,wasm_sha256:wasm.digest,receptor_url:receptor.url,receptor_sha256:receptor.digest,ligand_url:ligand.url,ligand_sha256:ligand.digest,artifact_url:prepared.url,artifact_sha256:prepared.digest,center:target.center,artifact_bytes:row.artifact.bytes,artifact_gzip_bytes:row.artifact.gzip_bytes};
await writeFile(out+'/device_manifest.json',JSON.stringify(manifest,null,2)+'\n');
const token=randomBytes(18).toString('hex'),page=await readFile('research/prepared_device_page.html'),worker=await readFile('research/prepared_device_worker.mjs'),sha=await readFile('research/prepared_sha256.mjs');let saved=0;const requests={};
createServer(async(req,res)=>{try{const url=new URL(req.url,'http://localhost'),a=assets.get(url.pathname);if(a){requests[url.pathname]=(requests[url.pathname]||0)+1;res.setHeader('Content-Type',a.type);res.setHeader('Cache-Control','public, max-age=31536000, immutable');res.setHeader('Vary','Accept-Encoding');const zipped=/gzip/.test(req.headers['accept-encoding']||'');if(zipped)res.setHeader('Content-Encoding','gzip');res.setHeader('Content-Length',(zipped?a.gzip:a.bytes).length);res.end(zipped?a.gzip:a.bytes);return;}
res.setHeader('Cache-Control','no-store');if(url.pathname==='/worker.mjs'||url.pathname==='/sha.mjs'){res.setHeader('Content-Type','text/javascript');res.end(url.pathname==='/worker.mjs'?worker:sha);return;}
if(url.searchParams.get('key')!==token){res.writeHead(403).end('Use full link');return;}
if(url.pathname==='/'){res.setHeader('Content-Type','text/html; charset=utf-8');res.end(page);return;}
if(url.pathname==='/manifest'){res.setHeader('Content-Type','application/json');res.end(JSON.stringify(manifest));return;}
if(url.pathname==='/results'&&req.method==='POST'){let n=0,parts=[];for await(const p of req){n+=p.length;if(n>10000000){res.writeHead(413).end();return;}parts.push(p);}const r=JSON.parse(Buffer.concat(parts));if(!Array.isArray(r.runs)||r.runs.length>4||saved>=100)throw Error('Bounds');const expected=row.modes.find(m=>m.mode==='reference').tasks;r.checks=r.runs.map(x=>({index:x.index,exact:expected[x.index]?.pool===hash(String(x.pool))&&expected[x.index]?.trace===hash(String(x.trace))}));r.server_asset_requests={...requests};r.server_received_at=new Date().toISOString();const id=Date.now()+'-'+randomBytes(4).toString('hex');await writeFile(out+'/device_'+id+'.json',JSON.stringify(r,null,2)+'\n');saved++;console.log('RESULT',id,r.device_model,r.checks);res.setHeader('Content-Type','application/json');res.end(JSON.stringify({id,runs:r.runs.length,matches:r.checks.filter(x=>x.exact).length}));return;}
res.writeHead(404).end();}catch(e){console.error(String(e));res.writeHead(400).end('Invalid request');}}).listen(port,httpsTest?'127.0.0.1':'0.0.0.0',()=>{const urls=Object.values(os.networkInterfaces()).flat().filter(x=>x.family==='IPv4'&&!x.internal).map(x=>'http://'+x.address+':'+port+'/?key='+token);const info={urls,local:'http://127.0.0.1:'+port+'/?key='+token};console.log(info);writeFile(httpsTest?'tmp/vina-prepared-https-local-url.json':idb?'tmp/vina-prepared-idb-url.json':'tmp/vina-prepared-url.json',JSON.stringify(info));});
